-- MySQL Script generated by MySQL Workbench
-- Wed Jul  8 12:21:31 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `escuela` ;

-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escuela` DEFAULT CHARACTER SET utf8 ;
USE `escuela` ;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tipos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carreras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carreras` ;

CREATE TABLE IF NOT EXISTS `carreras` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fundacion` DATE NULL DEFAULT NULL,
  `descripcion` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupos` ;

CREATE TABLE IF NOT EXISTS `grupos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `turno` VARCHAR(45) NOT NULL,
  `carrera` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alumnos` ;

CREATE TABLE IF NOT EXISTS `alumnos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `a_paterno` VARCHAR(45) NOT NULL,
  `a_materno` VARCHAR(45) NOT NULL,
  `usuario` INT(11) NOT NULL,
  `grupo` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materias` ;

CREATE TABLE IF NOT EXISTS `materias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `decripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `unidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unidades` ;

CREATE TABLE IF NOT EXISTS `unidades` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `materia` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `criterios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `criterios` ;

CREATE TABLE IF NOT EXISTS `criterios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `porcentaje` VARCHAR(45) NOT NULL,
  `unidad` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `calificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `calificaciones` ;

CREATE TABLE IF NOT EXISTS `calificaciones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `calificacion` DECIMAL(10,2) NOT NULL,
  `observacion` VARCHAR(45) NOT NULL,
  `criterio` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `profesores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `profesores` ;

CREATE TABLE IF NOT EXISTS `profesores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rfc` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `a_paterno` VARCHAR(45) NOT NULL,
  `a_materno` VARCHAR(45) NOT NULL,
  `usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `asignaturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asignaturas` ;

CREATE TABLE IF NOT EXISTS `asignaturas` (
  `materia` INT(11) NOT NULL,
  `grupo` INT(11) NOT NULL,
  `profesor` INT(11) NOT NULL,
  PRIMARY KEY (`materia`, `grupo`, `profesor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Data for table `usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `escuela`;
INSERT INTO `usuarios` (`id`, `user`, `password`, `tipos`) VALUES (1, 'admin', 'admin', 'Administrativos');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
